import { DayRoutine } from './types';

// Helper to convert Shorts URL to Embed
const getEmbed = (shortsId: string) => `https://www.youtube.com/embed/${shortsId}?autoplay=1&mute=1&loop=1&playlist=${shortsId}`;

// Daily Warmup/Cardio Routine (Included in Daily Workout)
const DAILY_CARDIO = [
  {
    name: 'Stretching',
    sets: 1,
    repsOrDuration: '10 Mins',
    category: 'Warmup',
    instructions: ['Perform full body dynamic stretching'],
  },
  {
    name: 'Walking',
    sets: 1,
    repsOrDuration: '1 Hour',
    category: 'Cardio',
    instructions: ['Steady state walking'],
  },
  {
    name: 'Running / Jogging',
    sets: 1,
    repsOrDuration: '1 Hour',
    category: 'Cardio',
    instructions: ['Maintain consistent pace'],
  }
];

export const WORKOUT_SCHEDULE: DayRoutine[] = [
  {
    id: 'day_1',
    dayName: 'Saturday',
    focus: 'Chest + Triceps + Core',
    isRestDay: false,
    exercises: [
      ...DAILY_CARDIO.map((ex, i) => ({ ...ex, id: `sat_warmup_${i}` })),
      {
        id: 'sat_1',
        name: 'Normal Push-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Chest',
        videoUrl: getEmbed('4Bc1tPaYkOo'),
        instructions: ['Keep body straight', 'Lower chest to floor', 'Push back up explosively'],
      },
      {
        id: 'sat_2',
        name: 'Single-arm Dumbbell Floor Press',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Chest',
        videoUrl: getEmbed('rk8YayRoTRQ'),
        instructions: ['Lie on floor', 'Press weight straight up', 'Control the descent'],
      },
      {
        id: 'sat_3',
        name: 'Wide-grip Push-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Chest',
        videoUrl: getEmbed('4Bc1tPaYkOo'),
        instructions: ['Hands wider than shoulder width', 'Target outer chest'],
      },
      {
        id: 'sat_4',
        name: 'Kneeling Triceps Kickback',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Triceps',
        videoUrl: getEmbed('WhBxKbe1-NU'),
        instructions: ['Knee on bench/floor', 'Extend arm back fully', 'Squeeze tricep at top'],
      },
      {
        id: 'sat_5',
        name: 'Seated Dumbbell Overhead Triceps Extension',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Triceps',
        videoUrl: getEmbed('b_r_LW4HEcM'),
        instructions: ['Keep elbows close to head', 'Lower weight behind head', 'Extend fully up'],
      },
      {
        id: 'sat_6',
        name: 'Diamond Push-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Triceps',
        videoUrl: getEmbed('4Bc1tPaYkOo'),
        instructions: ['Hands form a diamond shape', 'Target triceps', 'Keep core tight'],
      },
      {
        id: 'sat_7',
        name: 'Plank',
        sets: 2,
        repsOrDuration: '30s -> 45s -> 1m',
        category: 'Core',
        videoUrl: getEmbed('xe2MXatLTUw'),
        instructions: ['Progression: Start with 30s, build to 1m'],
      },
    ],
  },
  {
    id: 'day_2',
    dayName: 'Sunday',
    focus: 'Back + Biceps + Traps + Core',
    isRestDay: false,
    exercises: [
      ...DAILY_CARDIO.map((ex, i) => ({ ...ex, id: `sun_warmup_${i}` })),
      {
        id: 'sun_1',
        name: 'Dumbbell Bent-over Row',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Back',
        videoUrl: getEmbed('f8r7gA3nyb8'),
        instructions: ['Bent at hips', 'Back straight', 'Pull weights to hip'],
      },
      {
        id: 'sun_2',
        name: 'Pull-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Back',
        instructions: ['Hang from bar', 'Pull chin over bar', 'Control descent'],
      },
      {
        id: 'sun_3',
        name: 'Dumbbell Concentration Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Biceps',
        videoUrl: getEmbed('EjUnEEfTSEY'),
        instructions: ['Elbow against inner thigh', 'Curl weight up', 'Squeeze at top'],
      },
      {
        id: 'sun_4',
        name: 'Standing Dumbbell Biceps Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Biceps',
        videoUrl: getEmbed('_aoad2yuP5w'),
        instructions: ['Stand straight', 'Curl weights up', 'Do not swing body'],
      },
      {
        id: 'sun_5',
        name: 'Seated Dumbbell Inner Biceps Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Biceps',
        videoUrl: getEmbed('FwApweWh6SY'),
        instructions: ['Seated incline', 'Arms hang down', 'Curl outwards'],
      },
      {
        id: 'sun_6',
        name: 'Dumbbell Shrugs',
        sets: 2,
        repsOrDuration: '15 Reps',
        category: 'Traps',
        videoUrl: getEmbed('rFsSeClGnNA'),
        instructions: ['Lift shoulders to ears', 'Hold briefly', 'Lower slowly'],
      },
      {
        id: 'sun_7',
        name: 'Plank',
        sets: 2,
        repsOrDuration: '30s -> 45s -> 1m',
        category: 'Core',
        videoUrl: getEmbed('xe2MXatLTUw'),
        instructions: ['Progression: Start with 30s, build to 1m'],
      },
    ],
  },
  {
    id: 'day_3',
    dayName: 'Monday',
    focus: 'Legs + Abs + Kegel',
    isRestDay: false,
    exercises: [
      ...DAILY_CARDIO.map((ex, i) => ({ ...ex, id: `mon_warmup_${i}` })),
      {
        id: 'mon_abs_1',
        name: 'High Knee Jump',
        sets: 5,
        repsOrDuration: '1 min',
        category: 'Abs/Cardio',
        instructions: ['Jump driving knees up high', 'Maintain fast rhythm'],
      },
      {
        id: 'mon_abs_2',
        name: 'Jumping Jack',
        sets: 5,
        repsOrDuration: '1 min',
        category: 'Abs/Cardio',
        instructions: ['Standard jumping jacks'],
      },
      {
        id: 'mon_abs_3',
        name: 'Twister',
        sets: 5,
        repsOrDuration: '1 min',
        category: 'Abs',
        instructions: ['Standing or seated torso twist', 'Engage obliques'],
      },
      {
        id: 'mon_abs_4',
        name: 'Back Kick',
        sets: 5,
        repsOrDuration: '1 min',
        category: 'Abs/Cardio',
        instructions: ['Kick heels back towards glutes while jogging/standing'],
      },
      {
        id: 'mon_abs_5',
        name: 'Crunches',
        sets: 3,
        repsOrDuration: '15-20 Reps',
        category: 'Abs',
        instructions: ['Lie on back', 'Lift shoulders off ground', 'Contract abs'],
      },
      {
        id: 'mon_abs_6',
        name: 'Russian Twist',
        sets: 3,
        repsOrDuration: '15-20 Reps',
        category: 'Abs',
        instructions: ['Sit V-shape', 'Twist torso side to side', 'Hold weight if possible'],
      },
      {
        id: 'mon_abs_7',
        name: 'Leg Raises',
        sets: 3,
        repsOrDuration: '15-20 Reps',
        category: 'Abs',
        instructions: ['Lie flat', 'Lift legs to 90 degrees', 'Lower slowly without touching floor'],
      },
      {
        id: 'mon_abs_8',
        name: 'Scissors',
        sets: 3,
        repsOrDuration: '15-20 Reps',
        category: 'Abs',
        instructions: ['Lie flat', 'Criss-cross legs vertically or horizontally'],
      },
      {
        id: 'mon_abs_9',
        name: 'Alternating Heel Touches',
        sets: 3,
        repsOrDuration: 'Until Failure',
        category: 'Abs',
        videoUrl: getEmbed('3MNj7LrRX3U'),
        instructions: ['Lie on back, knees bent', 'Tap heels side to side', 'Engage obliques'],
      },
      {
        id: 'mon_abs_10',
        name: 'V-sit Rotation',
        sets: 2,
        repsOrDuration: '15 reps',
        category: 'Abs',
        instructions: ['Sit in V position', 'Rotate torso'],
      },
      {
        id: 'mon_abs_11',
        name: 'Bottom Ups',
        sets: 2,
        repsOrDuration: '15 reps',
        category: 'Abs',
        videoUrl: getEmbed('f_kidGMf25U'),
        instructions: ['Lie flat', 'Lift hips off ground driving feet to ceiling'],
      },
      {
        id: 'mon_legs_1',
        name: 'Squats',
        sets: 2,
        repsOrDuration: '30 Reps',
        category: 'Legs',
        instructions: ['Feet shoulder width', 'Sit back and down', 'Keep chest up'],
      },
      {
        id: 'mon_legs_2',
        name: 'Rocking Standing Calf Raise',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Legs',
        instructions: ['Stand tall', 'Rock forward onto toes', 'Squeeze calves'],
      },
      {
        id: 'mon_legs_3',
        name: 'Bodyweight Glute Bridges',
        sets: 2,
        repsOrDuration: '50 seconds',
        category: 'Legs',
        instructions: ['Lie on back, knees bent', 'Lift hips up', 'Squeeze glutes at top'],
      },
      {
        id: 'mon_kegel',
        name: 'Kegel Exercise',
        sets: 5,
        repsOrDuration: '1 min',
        category: 'Pelvic Floor',
        instructions: ['Contract pelvic floor muscles', 'Hold and release'],
      },
    ],
  },
  {
    id: 'day_4',
    dayName: 'Tuesday',
    focus: 'Shoulders + Arms + Forearms',
    isRestDay: false,
    exercises: [
      ...DAILY_CARDIO.map((ex, i) => ({ ...ex, id: `tue_warmup_${i}` })),
      {
        id: 'tue_sh_1',
        name: 'Seated Dumbbell Lateral Raise',
        sets: 2,
        repsOrDuration: '15 Reps',
        category: 'Shoulders',
        instructions: ['Raise arms to side', 'Elbows slightly bent', 'Stop at shoulder height'],
      },
      {
        id: 'tue_sh_2',
        name: 'Standing Dumbbell Front Raise',
        sets: 2,
        repsOrDuration: '15 Reps',
        category: 'Shoulders',
        instructions: ['Raise arm forward', 'Control the movement', 'Alternate arms'],
      },
      // Arms - Biceps (Any 2)
      {
        id: 'tue_arm_1',
        name: 'Standing Dumbbell Biceps Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Biceps',
        videoUrl: getEmbed('_aoad2yuP5w'),
        instructions: ['Standard curl'],
      },
      {
        id: 'tue_arm_2',
        name: 'Dumbbell Concentration Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Biceps',
        videoUrl: getEmbed('EjUnEEfTSEY'),
        instructions: ['Focus on the squeeze'],
      },
      // Arms - Triceps (Any 2)
      {
        id: 'tue_arm_3',
        name: 'Seated Dumbbell Overhead Ext',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Triceps',
        videoUrl: getEmbed('b_r_LW4HEcM'),
        instructions: ['Overhead extension'],
      },
      {
        id: 'tue_arm_4',
        name: 'Kneeling Triceps Kickback',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Triceps',
        videoUrl: getEmbed('WhBxKbe1-NU'),
        instructions: ['Kickback'],
      },
      {
        id: 'tue_for_1',
        name: 'Hammer Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Forearms',
        instructions: ['Palms facing each other', 'Curl straight up'],
      },
      {
        id: 'tue_for_2',
        name: 'Wrist Curl',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Forearms',
        instructions: ['Forearms on bench', 'Curl wrist up'],
      },
      {
        id: 'tue_for_3',
        name: 'Palm-up Forearm Hold',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Forearms',
        instructions: ['Hold weight with palms up', 'Keep static'],
      },
    ],
  },
  {
    id: 'day_5',
    dayName: 'Wednesday',
    focus: 'Chest + Back + Core',
    isRestDay: false,
    exercises: [
      ...DAILY_CARDIO.map((ex, i) => ({ ...ex, id: `wed_warmup_${i}` })),
      {
        id: 'wed_1',
        name: 'Normal Push-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Chest',
        videoUrl: getEmbed('4Bc1tPaYkOo'),
        instructions: ['Repeat Saturday Routine'],
      },
      {
        id: 'wed_2',
        name: 'Single-arm Dumbbell Floor Press',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Chest',
        videoUrl: getEmbed('rk8YayRoTRQ'),
        instructions: ['Repeat Saturday Routine'],
      },
      {
        id: 'wed_3',
        name: 'Wide-grip Push-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Chest',
        videoUrl: getEmbed('4Bc1tPaYkOo'),
        instructions: ['Repeat Saturday Routine'],
      },
      {
        id: 'wed_4',
        name: 'Dumbbell Bent-over Row',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Back',
        videoUrl: getEmbed('f8r7gA3nyb8'),
        instructions: ['Repeat Sunday Routine'],
      },
      {
        id: 'wed_5',
        name: 'Pull-up',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Back',
        instructions: ['Repeat Sunday Routine'],
      },
      {
        id: 'wed_6',
        name: 'Plank',
        sets: 2,
        repsOrDuration: '30s -> 45s -> 1m',
        category: 'Core',
        videoUrl: getEmbed('xe2MXatLTUw'),
        instructions: ['Progression'],
      },
    ],
  },
  {
    id: 'day_6',
    dayName: 'Thursday',
    focus: 'Legs + Shoulders + Kegel',
    isRestDay: false,
    exercises: [
      ...DAILY_CARDIO.map((ex, i) => ({ ...ex, id: `thu_warmup_${i}` })),
      {
        id: 'thu_1',
        name: 'Squats',
        sets: 2,
        repsOrDuration: '30 Reps',
        category: 'Legs',
        instructions: ['Deep stance', 'Explosive up'],
      },
      {
        id: 'thu_2',
        name: 'Rocking Standing Calf Raise',
        sets: 2,
        repsOrDuration: 'Until Failure',
        category: 'Legs',
        instructions: ['Focus on calf squeeze'],
      },
      {
        id: 'thu_3',
        name: 'Bodyweight Glute Bridges',
        sets: 2,
        repsOrDuration: '50 seconds',
        category: 'Legs',
        instructions: ['Squeeze glutes'],
      },
      {
        id: 'thu_4',
        name: 'Seated Dumbbell Lateral Raise',
        sets: 2,
        repsOrDuration: '15 Reps',
        category: 'Shoulders',
        instructions: ['Control the eccentric'],
      },
      {
        id: 'thu_5',
        name: 'Standing Dumbbell Front Raise',
        sets: 2,
        repsOrDuration: '15 Reps',
        category: 'Shoulders',
        instructions: ['Front deltoid focus'],
      },
      {
        id: 'thu_6',
        name: 'Kegel Exercise',
        sets: 5,
        repsOrDuration: '1 min',
        category: 'Pelvic Floor',
        instructions: ['Contract pelvic floor muscles', 'Hold and release'],
      },
    ],
  },
  {
    id: 'day_7',
    dayName: 'Friday',
    focus: 'Rest & Recovery',
    isRestDay: true,
    exercises: [
      {
        id: 'fri_1',
        name: 'Stretching',
        sets: 1,
        repsOrDuration: '5 Mins',
        category: 'Recovery',
        instructions: ['Light full body stretch'],
      },
      {
        id: 'fri_2',
        name: 'Walking',
        sets: 1,
        repsOrDuration: '10 Mins',
        category: 'Recovery',
        instructions: ['Light walking only', 'NO RUNNING'],
      }
    ],
  },
];
